### ISSUE TITLE
Provide a consolidated ICS (iCalendar) file to subscribe from the Phone

### ISSUE THREAD

**Issue by jcea** [Ingobernable/OkuPanel#1]
I rather prefer to automatically integrate the events in my phone calendar instead of explicitly visiting a webpage. Could you provide a consolidated ICS file for other systems?

**Comment by moon155** [comment]
Hi! Not much time to implement it right now, but that's a nice feature request indeed! Feel free to push some code ;)

**Comment by moon155** [comment]
This feature was just implemented! 
See https://github.com/Ingobernable/OkuPanel/pull/5
Cheers

**Comment by jcea** [comment]
Subscribed. It works. Thanks!
